name: Run Module Tests

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main, devel]
  workflow_dispatch:
    inputs:
      release_test_addn:
        description: "Controls whether additional release tests should be run."
        required: false
        default: "false"
        type: choice
        options: ["true", "false"]

jobs:
  test:
    uses: klaus-rindfrey/github-actions-perl/.github/workflows/perl-tests.yml@v1
    with:
      release_test_addn: ${{ inputs.release_test_addn }}
      matrix: |
        {
          "runner": ["ubuntu-latest", "macos-latest", "windows-latest"],
          perl: ["5.10", "5.36", "5.38"],
          "include": [
            { "runner": "ubuntu-latest", "perl": "5.14" },
            { "runner": "ubuntu-latest", "perl": "5.40" },
            { "runner": "ubuntu-latest", "perl": "5.42" }
          ]
        }

